
DROP SEQUENCE HIBERNATE_SEQUENCE ;
CREATE SEQUENCE  "XTJG"."HIBERNATE_SEQUENCE"  MINVALUE 1  INCREMENT BY 1 START WITH 1000 CACHE 100 NOORDER  NOCYCLE ; 

--初始化数据字典
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (1, 'USERTYPE', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '用户类型', '1', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (2, 'POST', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '职位', '2', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (3, 'JOB', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '职务', '3', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (4, 'POSTTITLE', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '职称', '4', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (5, 'JOBLEVEL', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '职级', '5', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (6, 'ROLETYPE', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '角色类型', '6', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (7, 'ORGTYPE', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '组织类型', '7', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (8, 'LOCALUSER', 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '本地用户', '0', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 1);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (11, 'ZYUSER', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '中油用户', '1', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 1);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (12, 'RESOURCETYPE', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '资源类型', '1', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (13, 'COMPANY', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '公司', '4', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 12);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (14, 'PAGE', 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', '页面', '2', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 12);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (15, 'BUTTON', 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', '按钮', '3', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 12);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (21, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '职位一', '21', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 2);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (22, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '职位二', '22', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 2);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (31, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '财务总监', '31', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (32, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '处长', '32', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (33, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '行政管理', '31', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (34, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '副处长', '32', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (35, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', 'HSE管理', '31', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (36, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '车间主任', '32', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (37, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '综合管理员', '31', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (38, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '劳资工程师', '32', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 3);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (41, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '职称一', '41', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 4);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (42, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '职称二', '42', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 4);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (51, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '职级一', '51', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 5);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (52, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '职级二', '52', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 5);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (53, 'LOGTYPE', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '日志类型', '1', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 1, '0', null);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (54, 'SYS_LOG', 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '系统日志', '2', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 53);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (56, 'ERR_LOG', 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '错误日志', '3', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 53);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (63, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '流程角色', '61', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 6);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (62, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '系统角色', '62', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 6);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (71, null, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', '公司', '71', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 7);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (72, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '部门', '72', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 7);
insert into T_DICTIONARY (PK_ID, DICT_CODE, DICT_UUID, DICTIONARY_NAME, DICTIONARY_VALUE, FK_DICT_TYPE_UUID, LEVEL_ORDER, STATUS, PARENT_ID) values (73, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', '装置', '72', 'DictionaryType-1c85e7a1-49cb-4ae4-8321-a7216f01d23a', 2, '0', 7);
-- 初始化组织数据
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (1, '大庆金桥', 'DQGB', null, 71, 0, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (2, '技术开发部', 'DQGB_JSB', 1, 72, 1, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (3, '研发中心', 'DQGB_YFZX', 1, 72, 2, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (4, '项目管理部', 'DQGB_XMGL', 1, 72, 3, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (5, '支持中心', 'DQGB_ZCZX', 1, 72, 4, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (6, '运维服务部', 'DQGB_YWFW', 1, 72, 5, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (7, '库房管理部', 'DQGB_KFGL', 1, 72, 6, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (8, '财务人事部', 'DQGB_CWRS', 1, 72, 7, 0, 0, 0, null, 1);
insert into T_ORGANIZATION (ORG_ID, ORG_NAME, ORG_CODE, PARENT_ID, FK_ORGTYPE, DIS_ORDER, ENABLE, STATUS, ORG_FROM, FK_ORGTYPE_UUID, ISDELETEABLE) values (9, '行政采购部', 'DQGB_XZCG', 1, 72, 8, 0, 0, 0, null, 1);
-- 初始化资源数据
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (35, '系统管理', 'XTGL', 14, 'XTGL', '系统管理', null, '5', 0, to_date('04-04-2014 09:31:44', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (2, '用户管理', 'YHGL', 14, 'user/toUserIndex.action', '用户管理页面跳转', 35, '4', 0, to_date('02-04-2014 10:57:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (3, '资源管理', 'ZYGL', 14, 'resource/toResourceIndex.action', '资源管理页面跳转', 35, '7', 0, to_date('28-03-2014 09:15:59', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (4, '角色管理', 'JSGL', 14, 'role/toRoleIndex.action', '角色管理页面跳转', 35, '8', 0, to_date('28-03-2014 11:42:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (5, '组织管理', 'ZZGL', 14, 'org/toOrgIndex.action', '组织管理页面跳转', 35, '5', 0, to_date('04-04-2014 10:06:27', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (6, '字典管理', 'ZDGL', 14, 'dict/toDictIndex.action', '字典管理页面跳转', 35, '10', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (7, '日志管理', 'RZGL', 14, 'log/toLogIndex.action', '日志管理页面跳转', 35, '11', 0, to_date('12-09-2014 16:11:41', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (8, '流程管理', 'LCGL', 14, 'bpm/toProcessManage.action', '流程管理页面跳转', null, '4', 0, to_date('27-03-2014 17:01:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (10, '用户管理-添加按钮', 'usermanage_add_btn', 15, '${ctx}/user/addUser.action', '用户管理-添加按钮', 2, '1', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (11, '用户管理-删除按钮', 'usermanage_delete_btn', 15, '${ctx}/user/deleteUser.action', '用户管理-删除按钮', 2, '2', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (12, '用户管理-修改按钮', 'usermanage_update_btn', 15, '${ctx}/user/editUser.action', '用户管理-修改按钮', 2, null, 0, to_date('28-03-2014 16:39:27', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (13, '用户管理-EXCEL操作按钮组', 'usermanage_excel_btn', 15, null, '用户管理-EXCEL操作按钮组', 2, '4', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (14, '用户管理-EXCEL操作按钮组-用户导入按钮', 'usermanage_excel_userImp_btn', 15, '${ctx}/user/uploadExcelToBacthImportUser.action', '用户管理-EXCEL操作按钮组-用户导入按钮', 13, '1', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (15, '用户管理-EXCEL操作按钮组-用户导出按钮', 'usermanage_excel_userExp_btn', 15, '${ctx}/user/exportAllUsers.action', '用户管理-EXCEL操作按钮组-用户导出按钮', 13, '2', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (17, '用户管理-EXCEL操作按钮组-用户导入模版下载按钮', 'usermanage_excel_userImptemplate_btn', 15, '${ctx}/user/downloadUserExcelTemplate.action', '用户管理-EXCEL操作按钮组-用户导入模版下载按钮', 13, '4', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (19, '角色管理-添加按钮', 'rolemanage_add_btn', 15, '/role/addRole.action', '角色管理-添加按钮', 4, null, 0, to_date('29-09-2014 16:41:22', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (20, '角色管理-删除按钮', 'rolemanage_delete_btn', 15, '${ctx}/role/updateRole.action', '角色管理-删除按钮', 4, null, 0, to_date('27-03-2014 17:00:36', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (21, '角色管理-修改按钮', 'rolemanage_update_btn', 15, '${ctx}/role/deleteRole.action', '角色管理-修改按钮', 4, '3', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (22, '资源管理-添加父级菜单', 'resourcemanage_addpra_btn', 15, '${ctx}/resource/addResource.action', '资源管理-添加父级菜单', 3, '1', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (23, '资源管理-添加菜单', 'resourcemanage_add_btn', 15, '${ctx}/resource/addResource.action', '资源管理-添加菜单', 3, '2', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (24, '资源管理-删除菜单', 'resourcemanage_delete_btn', 15, '${ctx}/resource/deleteResource.action', '资源管理-删除菜单', 3, '3', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (25, '资源管理-修改菜单', 'resourcemanage_update_btn', 15, '${ctx}/resource/editResource.action', '资源管理-修改菜单', 3, '4', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (26, '组织管理-添加组织', 'organization_addOrg_btn', 15, '${ctx}/org/addOrg.action', '组织管理-添加组织', 5, null, 0, to_date('28-03-2014 14:28:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (27, '组织管理-删除组织', 'organization_deleteOrg_btn', 15, '${ctx}/org/delOrg.action', '组织管理-删除组织', 5, '2', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (28, '用户管理-同步按钮', 'usermanage_synch_btn', 15, '${ctx}/user/synchronizeUserInfo.action', '用户管理-同步按钮', 2, '5', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (29, '角色管理-同步按钮', 'rolemanage_synch_btn', 15, '${ctx}/role/synchronizeRoleInfo.action', '角色管理-同步按钮', 4, '4', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (30, '资源管理-同步按钮', 'resourcemanage_synch_btn', 15, '${ctx}/resource/synchronizeResourceInfo.action', '资源管理-同步按钮', 3, '5', 0, to_date('10-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (31, '组织管理-同步按钮', 'organization_synch_btn', 15, '${ctx}/org/synchOrgData.action', '组织管理-同步按钮', 5, null, 0, to_date('28-03-2014 16:10:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (34, '组织管理-修改按钮', 'organization_update_btn', 15, '${ctx}/org/updateOrg.action', '组织管理-修改按钮', 5, '5', 0, to_date('25-02-2014', 'dd-mm-yyyy'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 1);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (37, '字典管理-修改按钮', 'dict_update_btn', 15, '${ctx}/dict/updateDictInfo.action', '字典管理-修改按钮', 6, null, 0, to_date('12-09-2014 16:12:06', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (38, '字典管理-添加按钮', 'dict_add_btn', 15, '${ctx}/dict/addDictInfo.action', '字典管理-添加按钮', 6, null, 0, to_date('02-09-2014 09:32:11', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (39, '字典管理-删除按钮', 'dict_delete_btn', 15, '${ctx}/dict/deleteTypes.action', '字典管理-删除按钮', 6, null, 0, to_date('02-09-2014 09:32:21', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (40, '个人中心', 'GRZX', 14, 'bpm/toPersonManage.action', '个人中心', null, '1', 0, to_date('20-01-2015 09:51:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (41, '班组管理', 'BZGL', 14, 'workteam/toWorkTeam.action', '班组管理页面跳转', 35, '12', 0, to_date('01-09-2014 17:28:23', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (42, '班次管理', 'BCGL', 14, 'workturns/toRoundPage.action', '班次管理页面跳转', 35, '13', 0, to_date('01-09-2014 17:28:10', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (43, '倒班管理', 'DBGL', 14, 'workturnsrule/toWorkTurnsRuleManage.action', '倒班管理页面跳转', 35, '14', 0, to_date('01-09-2014 17:28:00', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (44, '班组管理-添加按钮', 'workteam_add_btn', 15, 'workteam_add_btn', '添加按钮', 41, null, 0, to_date('02-09-2014 08:28:24', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (45, '班组管理-修改按钮', 'workteam_update_btn', 15, 'workteam_update_btn', '修改按钮', 41, null, 0, to_date('02-09-2014 08:29:15', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (46, '班组管理删除按钮', 'workteam_delete_btn', 15, 'workteam_delete_btn', '删除按钮', 41, null, 0, to_date('02-09-2014 08:30:01', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (47, '班次管理-添加按钮', 'workround_add_btn', 15, 'workround_add_btn', '添加按钮', 42, null, 0, to_date('02-09-2014 08:31:28', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (48, '班次管理-修改按钮', 'workround_update_btn', 15, 'workround_update_btn', '修改按钮', 42, null, 0, to_date('02-09-2014 08:32:09', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (49, '班次管理-删除按钮', 'workround_delete_btn', 15, 'workround_delete_btn', '删除按钮', 42, null, 0, to_date('02-09-2014 08:32:50', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (50, '倒班管理-添加按钮', 'turnsrule_add_btn', 15, 'turnsrule_add_btn', '添加按钮', 43, null, 0, to_date('02-09-2014 08:33:57', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (51, '倒班管理-修改按钮', 'turnsrule_update_btn', 15, 'turnsrule_update_btn', '修改按钮', 43, null, 0, to_date('02-09-2014 08:34:53', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (52, '倒班管理-删除按钮', 'turnsrule_delete_btn', 15, 'turnsrule_delete_btn', '删除按钮', 43, null, 0, to_date('02-09-2014 08:35:32', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7c396583-7f52-4ef0-9973-2cbf3e9e573e', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (53, '群组管理', 'QZGL', 14, 'group/toGroupManagementIndex.action', '群组管理', 35, '6', 0, to_date('15-09-2014 14:06:22', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (54, '添加按钮', 'group_add_btn', 15, 'group_add_btn', '群组_添加', 53, null, 0, to_date('15-09-2014 14:10:17', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (55, '删除按钮', 'group_delete_btn', 15, 'group_delete_btn', '群组_删除', 53, null, 0, to_date('15-09-2014 14:10:22', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (56, '修改按钮', 'group_update_btn', 15, 'group_update_btn', '群组_修改', 53, null, 0, to_date('15-09-2014 14:10:27', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (57, '成员添加按钮', 'group_member_add_btn', 15, 'group_member_add_btn', '成员添加按钮', 53, null, 0, to_date('15-09-2014 14:11:13', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (58, '成员删除按钮', 'group_member_delete_btn', 15, 'group_member_delete_btn', '成员删除按钮', 53, null, 0, to_date('15-09-2014 14:11:51', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (59, '角色授权', 'QXGL', 14, 'role/toRoleMember.action', '角色成员页面跳转', 35, '9', 0, to_date('22-09-2014 09:39:02', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (60, '添加_用户', 'add_role_user_btn', 15, 'add_role_user_btn', '添加_用户', 59, null, 0, to_date('22-09-2014 10:18:25', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (61, '删除_用户', 'delete_role_user_btn', 15, 'delete_role_user_btn', '删除_用户', 59, null, 0, to_date('22-09-2014 10:19:14', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (62, '添加_群组', 'add_role_group_btn', 15, 'add_role_group_btn', '添加_群组', 59, null, 0, to_date('22-09-2014 10:20:07', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, RESOURCE_NAME, CODE, RESOURCE_TYPE, URLPATH, REMARKS, PARENT_ID, DIS_ORDER, STATUS, CREATE_DATE, RESOURCE_FROM, RESOURCE_TYPE_UUID, ISDELETEABLE) values (63, '删除_群组', 'delete_role_group_btn', 15, 'delete_role_group_btn', '删除_群组', 59, null, 0, to_date('22-09-2014 10:20:40', 'dd-mm-yyyy hh24:mi:ss'), 0, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', 0);
insert into T_RESOURCE (RESOURCE_ID, CODE, CREATE_DATE, DIS_ORDER, ISDELETEABLE, REMARKS, RESOURCE_FROM, RESOURCE_NAME, RESOURCE_TYPE_UUID, STATUS, URLPATH, PARENT_ID, RESOURCE_TYPE) values (64, 'ZDXX', to_date('22-05-2015 10:35:52', 'dd-mm-yyyy hh24:mi:ss'), 8, 0, null, 0, '站点信息', 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 0, 'site/index.html', null, 14);
insert into T_RESOURCE (RESOURCE_ID, CODE, CREATE_DATE, DIS_ORDER, ISDELETEABLE, REMARKS, RESOURCE_FROM, RESOURCE_NAME, RESOURCE_TYPE_UUID, STATUS, URLPATH, PARENT_ID, RESOURCE_TYPE) values (65, 'TYKJ', to_date('09-07-2015 17:59:56', 'dd-mm-yyyy hh24:mi:ss'), 7, 0, null, 0, '通用控件', 'Dictionary-c2065724-3d53-4bf7-b29a-8b57e61c0976', 0, 'examples/index.jsp', null, 14);

-- 初始化用户数据
insert into T_USER (USER_ID, USERNAME, ERP_ID, PASSWORD, MOBILE_PHONE1, ELECTRONIC_SIGNATURE, PERSONAL_IMAGE, REALNAME, GENDER, STATUS,DIS_ORDER, ISENABLE, FK_TYPE, USER_ONLINE, FK_TEAM, SHORT_NO1, PHONE_NO, BIRTH_PLACE, EMAIL, CARD_CODE, ID_CARD, FK_POSTTITLE, FK_POST, FK_JOB1, FK_JOBLEVEL, BIRTHDAY, ISDELETABLE, MOBILE_PHONE2, SHORT_NO2, FK_JOB2, FK_USERTYPE_UUID, FK_TEAM_UUID, FK_POSTTITLE_UUID, FK_POST_UUID, FK_JOB1_UUID, FK_JOB2_UUID, FK_JOBLEVEL_UUID) values (1, 'jg_admin', '111111', 'e10adc3949ba59abbe56e057f20f883e', '12345678911', null, null, '管理员', '男', 0, 0, 0, 8, 0, null, null, null, null, null, null, null, null, null, null, null, null, 0, null, null, null, 'Dictionary-d9e3b576-6880-4d15-aff8-97fba5daf111', null, null, null, null, null, null);
-- 初始化用户组织关系
insert into T_ORG_USER (PK_ORG_USER_ID, FK_ORG_ID, FK_USER_ID, ISDELETE) values (1, 1, 1, 0);
-- 初始化角色数据
insert into T_ROLE (ROLE_ID, ROLE_NAME, ROLE_CODE, DESCRIPTION, ISDELETE, FK_ROLE_TYPE, FK_ROLE_TYPE_UUID, ISDELETEABLE) values (1, '管理员', 'admin', 'administrator', 0, 61, 'Dictionary-7b90b11c-54de-4901-9f5b-3dd8f66fa0b1', 0);
-- 初始化角色资源关系数据
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (2, 37, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (4, 4, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (5, 21, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (6, 29, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (7, 19, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (8, 20, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (9, 6, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (10, 57, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (11, 38, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (12, 39, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (13, 8, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (14, 7, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (15, 2, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (16, 10, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (17, 11, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (18, 13, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (19, 14, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (20, 15, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (21, 17, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (22, 28, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (23, 12, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (24, 3, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (25, 22, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (26, 23, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (27, 24, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (28, 25, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (29, 30, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (30, 5, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (31, 27, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (32, 34, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (33, 26, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (34, 31, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (35, 55, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (36, 54, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (37, 53, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (38, 58, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (39, 52, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (40, 51, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (41, 50, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (42, 49, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (43, 48, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (44, 47, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (45, 40, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (46, 41, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (47, 42, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (48, 43, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (49, 35, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (50, 44, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (51, 45, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (52, 46, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (53, 56, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (54, 62, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (55, 63, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (56, 61, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (57, 59, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (58, 60, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (59, 64, 1);
insert into T_ROLE_RESOURCE (ROLE_RESOURCE_ID, RESOURCE_ID, ROLE_ID) values (60, 65, 1);
-- 初始化用户角色权限范围关系
insert into T_ROLE_MEMBER_SCOPE (ID, ROLE_ID, USER_ID, GROUP_ID) values (1, 1, 1, null);
-- 权限范围
insert into T_SCOPE_MEMBER (ID, ROLE_MEMBER_ID, ORG_ID) values (1, 1, 3);
insert into T_SCOPE_MEMBER (ID, ROLE_MEMBER_ID, ORG_ID) values (2, 1, 1);
insert into T_SCOPE_MEMBER (ID, ROLE_MEMBER_ID, ORG_ID) values (3, 1, 2);

comment on column SYS_ACTIVITI_PROCESS_INST.BUSINESS_ORG is '业务数据的归属组织ID';
comment on column SYS_ACTIVITI_PROCESS_INST.BUSINESS_ORG is '业务数据的归属组织ID';
comment on table T_DICTIONARY is '字典表';
comment on column T_DICTIONARY.PK_ID is '字典表主键';
comment on column T_DICTIONARY.DICTIONARY_NAME is '字典名称';
comment on column T_DICTIONARY.DICTIONARY_VALUE is '字典值';
comment on column T_DICTIONARY.LEVEL_ORDER is '等级或排序号';
comment on column T_DICTIONARY.STATUS is '删除标志 0未删除 1 已删除';
comment on column T_DICTIONARY.FK_DICT_TYPE_UUID is '字典类型随机数';
comment on column T_DICTIONARY.DICT_UUID is '字典数据随机数';
comment on column T_DICTIONARY.DICT_CODE is '字典编码';
comment on column T_DICTIONARY.PARENT_ID is '字典类型ID';
comment on table T_GROUP is '群组';
comment on column T_GROUP.GROUP_NAME is '群组名称';
comment on column T_GROUP.CREATE_DATE is '创建时间';
comment on column T_GROUP.REMARK is '备注';
comment on table T_GROUP_MEMBER is '群组成员';
comment on column T_GROUP_MEMBER.USER_ID is '用户ID';
comment on column T_GROUP_MEMBER.ORG_ID is '部门ID';
comment on column T_GROUP_MEMBER.GROUP_ID is '群组ID';
comment on table T_LOG is '日志表';
comment on column T_LOG.PK_LOG_ID is '日志表主键';
comment on column T_LOG.USER_ID is '操作人ID';
comment on column T_LOG.OP_DATE is '操作时间';
comment on column T_LOG.OP_CONTENT is '日志内容';
comment on column T_LOG.IP_URL is '操作IP地址';
comment on column T_LOG.LOG_TYPE is '日志类型 1系统日志，2，用户日志 3，系统错误日志';
comment on column T_LOG.FK_LOG_TYPE_UUID is '日志类型字典数据UUID';
comment on table T_ORGANIZATION is '组织表';
comment on column T_ORGANIZATION.ORG_CODE is '为了给用户使用方便，这里增加组织代码，例如：生产管理部的代码：SCGL';
comment on column T_ORGANIZATION.FK_ORGTYPE is '字典数据';
comment on column T_ORGANIZATION.DIS_ORDER is '同级排序';
comment on column T_ORGANIZATION.ENABLE is '0：可用；1：禁用';
comment on column T_ORGANIZATION.STATUS is '0：未删除 1：删除   2架构删除';
comment on column T_ORGANIZATION.ORG_FROM is '组织来源  0：架构自行添加     1：继承平台同步';
comment on column T_ORGANIZATION.FK_ORGTYPE_UUID is '组织类型字典数据UUID';
comment on column T_ORGANIZATION.ISDELETEABLE is '1不允许删除；0可以删除';
comment on table T_ORG_USER is '用户-组织表';
comment on column T_ORG_USER.PK_ORG_USER_ID is '主键';
comment on column T_ORG_USER.FK_ORG_ID is '组织ID';
comment on column T_ORG_USER.FK_USER_ID is '用户ID';
comment on column T_ORG_USER.ISDELETE is '0：未删除  1：已删除';
comment on table T_RESOURCE is '资源表';
comment on column T_RESOURCE.RESOURCE_ID is '主键';
comment on column T_RESOURCE.RESOURCE_NAME is '资源名称';
comment on column T_RESOURCE.CODE is '资源编码';
comment on column T_RESOURCE.RESOURCE_TYPE is '字典数据';
comment on column T_RESOURCE.URLPATH is '该字段可以存储菜单或页面的URL';
comment on column T_RESOURCE.REMARKS is '备注';
comment on column T_RESOURCE.PARENT_ID is '父菜单ID';
comment on column T_RESOURCE.DIS_ORDER is '从1开始排序';
comment on column T_RESOURCE.STATUS is '0：未删除 1：已删除 2：同步时删除';
comment on column T_RESOURCE.CREATE_DATE is '录入时间';
comment on column T_RESOURCE.RESOURCE_FROM is '资源来源 0：架构自行添加 1：集成平台同步';
comment on column T_RESOURCE.RESOURCE_TYPE_UUID is '资源类型字典数据UUID';
comment on column T_RESOURCE.ISDELETEABLE is '1不允许删除；0可以删除';
comment on table T_ROLE is '角色表';
comment on column T_ROLE.ROLE_ID is '主键';
comment on column T_ROLE.ROLE_NAME is '角色名';
comment on column T_ROLE.ROLE_CODE is '角色编码';
comment on column T_ROLE.DESCRIPTION is '描述';
comment on column T_ROLE.ISDELETE is '删除标志：0未删除 1已删除';
comment on column T_ROLE.FK_ROLE_TYPE is '角色种类：0：自有角色 1：授权角色';
comment on column T_ROLE.FK_ROLE_TYPE_UUID is '角色种类字典数据UUID';
comment on column T_ROLE.ISDELETEABLE is '1不允许删除；0可以删除';
comment on table T_ROLE_MEMBER_SCOPE is '角色、角色成员、有效范围的关联表';
comment on column T_ROLE_MEMBER_SCOPE.ROLE_ID is '角色ID';
comment on column T_ROLE_MEMBER_SCOPE.USER_ID is '用户ID';
comment on column T_ROLE_MEMBER_SCOPE.GROUP_ID is '群组的ID';
comment on table T_ROLE_RESOURCE is '角色资源表';
comment on column T_ROLE_RESOURCE.ROLE_RESOURCE_ID is '主键';
comment on column T_ROLE_RESOURCE.RESOURCE_ID is '资源ID';
comment on column T_ROLE_RESOURCE.ROLE_ID is '角色ID';
comment on column T_ROLE_TEMP_TEAM_MAP.RULE_ID is '倒班规则ID';
comment on column T_ROLE_TEMP_TEAM_MAP.RECYCLE_NUMBER is '周期号,表示一个周期内的第几天。';
comment on column T_ROLE_TEMP_TEAM_MAP.WORK_ROUND_ID is '班次ID';
comment on column T_ROLE_TEMP_TEAM_MAP.TEMP_TEAM_ID is '临时组ID';
comment on table T_RULE_WORK_TEAM_MAP is '倒班规则详细表';
comment on column T_RULE_WORK_TEAM_MAP.RULE_ID is '倒班规则ID';
comment on column T_RULE_WORK_TEAM_MAP.WORK_TEAM_ID is '班组ID';
comment on column T_RULE_WORK_TEAM_MAP.RECYCLE_NUMBER is '周期号,表示一个周期内的第几天。';
comment on column T_RULE_WORK_TEAM_MAP.WORK_ROUND_ID is '班次ID';
comment on table T_SCOPE_MEMBER is '权限范围';
comment on column T_SCOPE_MEMBER.ROLE_MEMBER_ID is '角色成员ID';
comment on column T_SCOPE_MEMBER.ORG_ID is '组织ID';
comment on table T_USER is '用户表';
comment on column T_USER.USER_ID is '主键';
comment on column T_USER.USERNAME is '登录名';
comment on column T_USER.ERP_ID is 'ERP编号';
comment on column T_USER.PASSWORD is '密码';
comment on column T_USER.MOBILE_PHONE1 is '手机号码1';
comment on column T_USER.ELECTRONIC_SIGNATURE is '电子签名';
comment on column T_USER.PERSONAL_IMAGE is '个人头像';
comment on column T_USER.REALNAME is '真实姓名';
comment on column T_USER.GENDER is '性别';
comment on column T_USER.STATUS is '0：未删除 1：已删除';
comment on column T_USER.DIS_ORDER is '排序';
comment on column T_USER.ISENABLE is '0:未禁用；1：禁用';
comment on column T_USER.FK_TYPE is '用户类型-字典表';
comment on column T_USER.USER_ONLINE is '最后在线时刻(用毫秒表示)';
comment on column T_USER.FK_TEAM is '班组';
comment on column T_USER.SHORT_NO1 is '集团短号1';
comment on column T_USER.PHONE_NO is '座机号码';
comment on column T_USER.BIRTH_PLACE is '出生地';
comment on column T_USER.EMAIL is '邮箱';
comment on column T_USER.CARD_CODE is '卡号';
comment on column T_USER.ID_CARD is '身份证号';
comment on column T_USER.FK_POSTTITLE is '职称-字典表';
comment on column T_USER.FK_POST is '职位-字典表';
comment on column T_USER.FK_JOB1 is '职务1-字典表';
comment on column T_USER.FK_JOBLEVEL is '职级-字典表';
comment on column T_USER.BIRTHDAY is '出生日期';
comment on column T_USER.ISDELETABLE is '是否允许删除： 0 允许  1 不允许';
comment on column T_USER.MOBILE_PHONE2 is '手机号码2';
comment on column T_USER.SHORT_NO2 is '集团短号2';
comment on column T_USER.FK_JOB2 is '职务2-字典表';
comment on column T_USER.FK_USERTYPE_UUID is '用户类型字典数据UUID';
comment on column T_USER.FK_TEAM_UUID is '班组字典数据UUID';
comment on column T_USER.FK_POSTTITLE_UUID is '职称字典数据UUID';
comment on column T_USER.FK_POST_UUID is '职位字典数据UUID';
comment on column T_USER.FK_JOB1_UUID is '职务1字典数据UUID';
comment on column T_USER.FK_JOB2_UUID is '职务2字典数据UUID';
comment on column T_USER.FK_JOBLEVEL_UUID is '职级字典数据UUID';