ALTER TABLE `t_personal_grade`
ADD COLUMN `RESPONSIBILITY_CODE`  varchar(255) NULL AFTER `POST_ABILITY`,
ADD COLUMN `RESPONSIBILITY_NAME`  varchar(255) NULL AFTER `RESPONSIBILITY_CODE`,
ADD COLUMN `ORG_NAME`  varchar(255) NULL AFTER `RESPONSIBILITY_NAME`,
ADD COLUMN `ORG_CODE`  varchar(255) NULL AFTER `ORG_NAME`,
ADD COLUMN `RESP_CHANGE_DATE`  varchar(50) NULL AFTER `ORG_CODE`;