ALTER TABLE `t_finalscore`
ADD COLUMN `PARTY_SCORE`  varchar(255) NULL COMMENT '党建' AFTER `PLUSED_SCORE`,
ADD COLUMN `ZHZL_SCORE`  varchar(255) NULL COMMENT '综合治理' AFTER `PARTY_SCORE`,
ADD COLUMN `SEC_SCORE`  varchar(255) NULL COMMENT '保密' AFTER `ZHZL_SCORE`,
ADD COLUMN `LH_SCORE`  varchar(255) NULL COMMENT '例会' AFTER `SEC_SCORE`;

UPDATE `gradesys`.`t_dictionary` SET `DICTIONARY_VALUE`='0.42' WHERE (`PK_ID`='4053');
UPDATE `gradesys`.`t_dictionary` SET `DICTIONARY_VALUE`='0.14' WHERE (`PK_ID`='4054');
UPDATE `gradesys`.`t_dictionary` SET `DICTIONARY_VALUE`='0.14' WHERE (`PK_ID`='4067');

INSERT INTO `gradesys`.`t_dictionary` (`PK_ID`, `DICT_CODE`, `DICT_UUID`, `DICTIONARY_NAME`, `DICTIONARY_VALUE`, `FK_DICT_TYPE_UUID`, `LEVEL_ORDER`, `STATUS`, `PARENT_ID`) VALUES ('4068', 'PARTYSCORE', NULL, '党建', '0.15', NULL, '4', '0', '4052');
INSERT INTO `gradesys`.`t_dictionary` (`PK_ID`, `DICT_CODE`, `DICT_UUID`, `DICTIONARY_NAME`, `DICTIONARY_VALUE`, `FK_DICT_TYPE_UUID`, `LEVEL_ORDER`, `STATUS`, `PARENT_ID`) VALUES ('4069', 'ZHZLSCORE', NULL, '综合治理', '0.05', NULL, '5', '0', '4052');
INSERT INTO `gradesys`.`t_dictionary` (`PK_ID`, `DICT_CODE`, `DICT_UUID`, `DICTIONARY_NAME`, `DICTIONARY_VALUE`, `FK_DICT_TYPE_UUID`, `LEVEL_ORDER`, `STATUS`, `PARENT_ID`) VALUES ('4070', 'SECSCORE', NULL, '保密', '0.05', NULL, '6', '0', '4052');
INSERT INTO `gradesys`.`t_dictionary` (`PK_ID`, `DICT_CODE`, `DICT_UUID`, `DICTIONARY_NAME`, `DICTIONARY_VALUE`, `FK_DICT_TYPE_UUID`, `LEVEL_ORDER`, `STATUS`, `PARENT_ID`) VALUES ('4071', 'LHSCORE', NULL, '例会', '0.05', NULL, '7', '0', '4052');
